config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

	def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save

    redirect_to flats_path
  end

  def edit
  end

  def update
    @flat.update(flat)

    redirect_to flats_path
  end

  def destroy
    @flat.destroy

    redirect_to flats_path
  end

  private
  def flat_params
    params.require(:pet).permit(:name, :species, :gender, :rescued_at)
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>All our flats</h1>
<h4>All <%= @flats.size%> flats</h4>
<div class="d-flex bg-light">
	<% @flats.each do |flat| %>
		<div class="card-trip">
			<img src="https://picsum.photos/200/300" />
			<div class="card-trip-infos">
				<div>
					<p><%= link_to "#{flat.name}", flat_path(flat) %></p>
					<p>Address: <%= flat.address %></p>
					<p><%= flat.price_per_night%> Number  <%= flat.number_of_guests%></p>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/flats/show.html.erb
<h1><%= @flat.name %></h1>
<p><%= @flat.address %></p>
<br>
<h2>A little bit about this flat</h2>
<p><%@flat.description%></p>

<h3><%@flat.price_per_night%></h3>
<h3><%@flat.number_of_guests%></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
  <nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <%= link_to "ADD", new_flat_path, class: 'btn btn-secondary' %>
  </nav>

  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>